### ISSUE TITLE
What about collection from Laravel ?

### ISSUE THREAD

**Issue by eXorus** [maxalmonte14/phpcollections#3]
Hello,

Good work, but I'm already use https://github.com/tightenco/collect that come from the code of Laravel Framework but can work for all PHP scripts.

Could you provide a comparison of features ?
https://laravel.com/docs/5.7/collections

Thanks

**Comment by maxalmonte14** [comment]
Laravel Collections provide a simple way to manipulate your arrays as objects, PHPCollections do too but also offer a more specific way to manipulate your data like languages as Java and C# do.

For example **you can not** store only values of a specific type in Laravel Collections, there is no type validation, so if you assume that all your values will be of the same type but they don't you can get a buggy behavior.

```php

/**
* In here we only need User objects
* but you can add other type values
*/
$users = collect([
    new User('Max'),
    new User('Vincent'),
    5,
]);

$users->each(function ($user, $key) {
    print $user->name;
});
```

That will result in an error like this:

`PHP Notice:  Trying to get property 'name' of non-object in index.php on line 4`

With PHPCollections you can save a headache and use `GenericList`, this collection allows you to specify what type of data you want to store in it.

```php
$users = new GenericList(
    User::class,
    new User('Max'),
    new User('Vincent')
);
$users->add(5); // An InvalidArgumentException is thrown!
```

If you want something more flexible you can use `ArrayList` which is essentially the same as a Laravel Collection

```php
$users = new ArrayList([
    new User('Max'),
    new ArrayObject(['name' => 'Vincent']),
    new StdClass(['name' => 'John']),
    'some random string',
]);
$users->add(5); // Everything is fine!
```

Also, the package offers two other collection types `Dictionary` and `Stack` for some other specific needs.

In terms of features Laravel Collections have a lot more, but that is because it is adapted to more generic needs, meanwhile PHPCollections have different collections for different needs, anyway you can find some common or similar methods in both packages like `first`, `last`, `map`, `forEach`, `sort`, `merge`, and some other for sure. PHPCollections is not intended to be a carbon copy of Laravel Collections but I got expired by them for sure.

Laravel Collections are great and offer a lot of great methods, I really enjoy working with Laravel Collections in my Laravel projects, my recommendation would be using Laravel Collections if you want arrays on steroids, or use PHPCollections if you want a more specific way for manipulating your data.

And why not? Use both of them!

**Comment by eXorus** [comment]
Nice explication. Thanks

**Comment by maxalmonte14** [comment]
Is there any other thing that you want to know about the package?

**Comment by eXorus** [comment]
No thanks, it was a very good answer I don't have any usage yet but I will think about this package if I need it one day.

**Comment by fgilio** [comment]
Thanks for the explanation!

**Comment by maxalmonte14** [comment]
You're welcome guys, you can ask me about any other doubt you may have now or in the future.

For the moment I will close this issue.
